# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('fips', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CostOfMeal',
            fields=[
                ('fips', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apiv1.County')),
                ('cost_per_meal', models.FloatField()),
                ('monthly_cost_one', models.FloatField()),
                ('monthly_cost_three', models.FloatField()),
                ('monthly_cost_four', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('fips', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apiv1.County')),
                ('median_housing_one', models.FloatField()),
                ('median_housing_three', models.FloatField()),
                ('median_housing_four', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMeal',
            fields=[
                ('fips', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='apiv1.County')),
                ('meal_supplement_in_dollar', models.FloatField()),
            ],
        ),
    ]
